# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_S <- function(n, i, L) {
    .Call(`_TestGLTM_compute_S`, n, i, L)
}

permutations <- function(n) {
    .Call(`_TestGLTM_permutations`, n)
}

h_tilde <- function(X1, X2, X3, X4, ind_eq, ind_ineq1, ind_ineq2) {
    .Call(`_TestGLTM_h_tilde`, X1, X2, X3, X4, ind_eq, ind_ineq1, ind_ineq2)
}

h <- function(L, ind_eq, ind_ineq1, ind_ineq2, perm) {
    .Call(`_TestGLTM_h`, L, ind_eq, ind_ineq1, ind_ineq2, perm)
}

calculate_H <- function(X, indices_U, ind_eq, ind_ineq1, ind_ineq2) {
    .Call(`_TestGLTM_calculate_H`, X, indices_U, ind_eq, ind_ineq1, ind_ineq2)
}

calculate_H_not_symmetric <- function(X, indices_U, ind_eq, ind_ineq1, ind_ineq2) {
    .Call(`_TestGLTM_calculate_H_not_symmetric`, X, indices_U, ind_eq, ind_ineq1, ind_ineq2)
}

g <- function(X, i, L, ind_eq, ind_ineq1, ind_ineq2, perm) {
    .Call(`_TestGLTM_g`, X, i, L, ind_eq, ind_ineq1, ind_ineq2, perm)
}

calculate_G <- function(X, L, ind_eq, ind_ineq1, ind_ineq2) {
    .Call(`_TestGLTM_calculate_G`, X, L, ind_eq, ind_ineq1, ind_ineq2)
}

compute_S_small <- function(n, i, L, K) {
    .Call(`_TestGLTM_compute_S_small`, n, i, L, K)
}

g_small <- function(X, i, L, n1, ind_eq, ind_ineq1, ind_ineq2, perm) {
    .Call(`_TestGLTM_g_small`, X, i, L, n1, ind_eq, ind_ineq1, ind_ineq2, perm)
}

calculate_G_small <- function(X, L, n1, ind_eq, ind_ineq1, ind_ineq2) {
    .Call(`_TestGLTM_calculate_G_small`, X, L, n1, ind_eq, ind_ineq1, ind_ineq2)
}

h_tilde_eq <- function(X1, X2, ind_eq) {
    .Call(`_TestGLTM_h_tilde_eq`, X1, X2, ind_eq)
}

h_eq <- function(L, ind_eq, perm) {
    .Call(`_TestGLTM_h_eq`, L, ind_eq, perm)
}

calculate_H_eq <- function(X, indices_U, ind_eq) {
    .Call(`_TestGLTM_calculate_H_eq`, X, indices_U, ind_eq)
}

calculate_H_not_symmetric_eq <- function(X, indices_U, ind_eq) {
    .Call(`_TestGLTM_calculate_H_not_symmetric_eq`, X, indices_U, ind_eq)
}

g_eq <- function(X, i, L, ind_eq, perm) {
    .Call(`_TestGLTM_g_eq`, X, i, L, ind_eq, perm)
}

calculate_G_eq <- function(X, L, ind_eq) {
    .Call(`_TestGLTM_calculate_G_eq`, X, L, ind_eq)
}

bootstrap <- function(E, H_centered) {
    .Call(`_TestGLTM_bootstrap`, E, H_centered)
}

bootstrap_m_dep <- function(E, B, omega, Y_centered) {
    .Call(`_TestGLTM_bootstrap_m_dep`, E, B, omega, Y_centered)
}

bootstrap_U <- function(E, H_centered, G_centered, N) {
    .Call(`_TestGLTM_bootstrap_U`, E, H_centered, G_centered, N)
}

