# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_S <- function(n, i, L) {
    .Call(`_TestGLTM_compute_S`, n, i, L)
}

permutations <- function(n) {
    .Call(`_TestGLTM_permutations`, n)
}

h_tilde <- function(X1, X2, X3, X4, ind_eq, ind_ineq1, ind_ineq2) {
    .Call(`_TestGLTM_h_tilde`, X1, X2, X3, X4, ind_eq, ind_ineq1, ind_ineq2)
}

h <- function(L, ind_eq, ind_ineq1, ind_ineq2, perm) {
    .Call(`_TestGLTM_h`, L, ind_eq, ind_ineq1, ind_ineq2, perm)
}

calculate_H <- function(X, indices_U, ind_eq, ind_ineq1, ind_ineq2) {
    .Call(`_TestGLTM_calculate_H`, X, indices_U, ind_eq, ind_ineq1, ind_ineq2)
}

calculate_H_not_symmetric <- function(X, indices_U, ind_eq, ind_ineq1, ind_ineq2) {
    .Call(`_TestGLTM_calculate_H_not_symmetric`, X, indices_U, ind_eq, ind_ineq1, ind_ineq2)
}

g <- function(X, i, L, ind_eq, ind_ineq1, ind_ineq2, perm) {
    .Call(`_TestGLTM_g`, X, i, L, ind_eq, ind_ineq1, ind_ineq2, perm)
}

calculate_G <- function(X, L, ind_eq, ind_ineq1, ind_ineq2) {
    .Call(`_TestGLTM_calculate_G`, X, L, ind_eq, ind_ineq1, ind_ineq2)
}

bootstrap_independent <- function(E, standardizer, Y_centered, p_eq) {
    .Call(`_TestGLTM_bootstrap_independent`, E, standardizer, Y_centered, p_eq)
}

bootstrap_m_dep <- function(E, B, omega, standardizer, Y_centered, p_eq) {
    .Call(`_TestGLTM_bootstrap_m_dep`, E, B, omega, standardizer, Y_centered, p_eq)
}

bootstrap_U <- function(E, H_centered, G_centered, N) {
    .Call(`_TestGLTM_bootstrap_U`, E, H_centered, G_centered, N)
}

