# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findn <- function(N, D) {
    .Call(`_TestGLTM_findn`, N, D)
}

calculate_Y_independent <- function(X, ind_eq, ind_ineq1, ind_ineq2) {
    .Call(`_TestGLTM_calculate_Y_independent`, X, ind_eq, ind_ineq1, ind_ineq2)
}

bootstrap_independent <- function(E, standardizer, Y_centered, p_eq) {
    .Call(`_TestGLTM_bootstrap_independent`, E, standardizer, Y_centered, p_eq)
}

