# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed <- function(seed) {
    invisible(.Call(`_RcppHelpers_set_seed`, seed))
}

calculate_Y <- function(indices, X1, X2) {
    .Call(`_RcppHelpers_calculate_Y`, indices, X1, X2)
}

bootstrap_independent <- function(E, standardizer, Y_centered, seeds) {
    .Call(`_RcppHelpers_bootstrap_independent`, E, standardizer, Y_centered, seeds)
}

bootstrap_dependent <- function(E, B, omega, standardizer, Y_centered) {
    .Call(`_RcppHelpers_bootstrap_dependent`, E, B, omega, standardizer, Y_centered)
}

fourth_mom <- function(S, a, b, c, d) {
    .Call(`_RcppHelpers_fourth_mom`, S, a, b, c, d)
}

compute_cov_Y <- function(S, indices) {
    .Call(`_RcppHelpers_compute_cov_Y`, S, indices)
}

